### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ArYaNKingo** [WANstorm/PossumBot#129]
![Uploading IMG_20211107_205527.jpg…]()
Hello dear possum dev
I was tried to activate the bot with start.sh and start.sh in my termux terminal emulator
But it gives the error
How can I fix it

Error in screenshot

**Comment by Barsik008** [comment]
@Aryankansotia I don't see the screenshot.

**Comment by Aryankansotia** [comment]
How can I send you screenshot

**Comment by Barsik008** [comment]
@Aryankansotia send a link or upload it here

**Comment by Aryankansotia** [comment]
Hello bro

I am too happy today
The possum bot now

**Comment by Barsik008** [comment]
@Aryankansotia It works?

**Comment by Aryankansotia** [comment]
In terminal it's shows the not activated but when I added it in server it's
commands not working

**Comment by Barsik008** [comment]
@Aryankansotia are intents enabled

**Comment by Aryankansotia** [comment]
What are intents and how to enable it

**Comment by Barsik008** [comment]
@Aryankansotia you can enable them in the discord bot settings

**Comment by Aryankansotia** [comment]
I will try
