### ISSUE TITLE
the commands are not working 

### ISSUE THREAD

**Issue by JZ1324** [WANstorm/PossumBot#147]
<img width="661" alt="Screen Shot 2022-09-12 at 10 26 24 pm" src="https://user-images.githubusercontent.com/91810297/189653052-ed2dad98-43d4-474e-b51d-dcb71bcccad9.png">

**Comment by WANstorm** [comment]
is the bot running?

**Comment by Julek-Git** [comment]
You must type it with bot name. For example:  ```@PossumBot !servernotgood```
